spring.application.name=shopease
spring.datasource.url=jdbc:postgresql://localhost:5432/shopease
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=1s
spring.elasticsearch.socket-timeout=30s

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000


# Razorpay
razorpay.key.id=rzp_test_Spy1rVEdPRL2Vn
razorpay.key.secret=1Bl0CheckrxUUdDwTpmNwhQW